version: '2'

services:
  app:
    image: 'ui-assignment:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=ui_test
      - SPRING_DATASOURCE_PASSWORD=ui_test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=ui_test
      - POSTGRES_PASSWORD=ui_test
      